### ISSUE TITLE
Move to Heroku

### ISSUE THREAD

**Issue by KitaitiMakoto** [iiirc/iiirc#158]

**Comment by KitaitiMakoto** [comment]
@banyan Could you confirm below?

1. Bump Ruby version to 2.3.1: https://github.com/iiirc/iiirc/commit/651823c53565134ca0118534f01f66d25a9abf7d
2. Install JawsDB addon: https://github.com/iiirc/iiirc/commit/651823c53565134ca0118534f01f66d25a9abf7d
3. Uninstall Heroku PostgreSQL addon to avoid Heroku env try to use pg gem automatically(we don't install it)
4. Set `JAWSDB_URL` according to JawsDB
5. Set `SECRET_TOKEN`, `NEWRELIC_LICENSE_KEY`, `  GITHUB_CLIENT_ID`, `GITHUB_CLIENT_SECRET`, `TWITTER_CONSUMER_KEY`, `TWITTER_CONSUMER_SECRET`, `TWITTER_ACCESS_TOKEN`,  `TWITTER_ACCESS_TOKEN_SECRET`, `GOOGLE_CUSTOM_SEARCH_CX` and `SNIPPET_SALT`
6. Set `DATABASE_URL` to same to `JAWSDB_URL` except for the scheme is `mysql2`
7. Drop `SYSLOG_URL` because the existence of this env var cause loading `remote_syslog_logger` gem that we droped
8. Use www.iiirc.org instead of iiirc.org: https://devcenter.heroku.com/articles/route-53

**Comment by KitaitiMakoto** [comment]
Changed Twitter profile: http://iiirc.org -> http://www.iiirc.org

**Comment by KitaitiMakoto** [comment]
No need to change tags for Twitter card.
No need to change Atom feed source code.

**Comment by banyan** [comment]
Changed Github OAtuth settings.

**Comment by banyan** [comment]
Pushed DB snapshot to bitbucket.

**Comment by KitaitiMakoto** [comment]
No need to change Google Analytics-related code.

**Comment by KitaitiMakoto** [comment]
Droped IRC notification on GitHub change.

**Comment by banyan** [comment]
Pushed current heroku env to Bitbucket.

**Comment by KitaitiMakoto** [comment]
Change hard-coded domains: https://github.com/iiirc/iiirc/commit/c8603438295bc435ac041faa2b2af809c7c725e9

**Comment by banyan** [comment]
Looks pretty good! 😂 https://github.com/iiirc/iiirc/issues/158#issuecomment-222347208

**Comment by KitaitiMakoto** [comment]
Thanks so much!
